### ISSUE TITLE
User Story: Setup Django and Cloudinary

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#12]
As a **developer**, I want Django and Cloudinary installed, so that I can create the initial Django app and connect it to Cloudinary as storage.

### ACCEPTANCE CRITERIA:
- Django, Cloudinary, and Pillows are successfully installed into the project.
- The Django API project is created.
- Settings.py is configured to include the Cloudinary storage

### TASKS:
- [x] Install Django, django-cloudinary-storage, and Pillows libraries.
- [x] Configure settings.py to include the Cloudinary storage by importing it as an environment variable.
- [x] Add ‘cloudinary_storage’ and ‘cloudinary’ in [setting.py](http://setting.py/)’s INSTALLED_APPS

**Comment by marked-gil** [comment]
User story completed.
