### ISSUE TITLE
User Store: Profile Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#14]
As a developer, I can automatically create a profile for each signed-up user so that they can add other personal information such as name, email, and profile picture.

### ACCEPTANCE CRITERIA:
- The Profile model includes fields, such as id, owner, first_name, last_name, image, email, datetime_created, datetime_updated, etc.
- The Profile model is available in the admin panel.

### TASKS:
- [x] Create the ‘profiles’ app
- [x] Add the ‘profiles’ app in setting.py’s INSTALLED_APPS
- [x] Create a Profile model with fields, such as id, owner, first_name, last_name, image, email, datetime_created, datetime_updated, etc.
- [x] Register the Profile model in the admin.py

**Comment by marked-gil** [comment]
User story completed.
