### ISSUE TITLE
User Story: Task Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#15]
As a developer, I can save in the database the tasks created by users so they can be returned on request.

### ACCEPTANCE CRITERIA:
- The Task Model includes fields, such as id, owner, task_name, description, description, date_created, date_updated, due_date, due_time, category, priority, progress, etc
- The Task model is available in the admin panel.

### TASKS:
- [ ] Create ‘tasks’ app
- [ ] Add the ‘tasks’ app in setting.py’s INSTALLED_APPS
- [ ] Create a Task Model with fields, such as id, owner, task_name, description, description, date_created, date_updated, due_date, due_time, category, priority, progress, etc.
- [ ] Register the Task Model in the admin.py
