### ISSUE TITLE
User Story: SharedTask Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#16]
As a developer, I can copy tasks that are shared among users and save them separately in the database so they are easy to identify and return on request.

### ACCEPTANCE CRITERIA:
- The sharedTask model includes fields, such as id, task, shared_to, datetime_created, datetime_updated, etc.
- The SharedTask model is available in the admin panel.

### TASKS:
- [x] Create ‘shared_tasks’ app
- [x] Add the ‘shared_tasks’ app in setting.py’s INSTALLED_APPS
- [x] Create SharedTask model with fields, such as id, task, shared_to, datetime_created, datetime_updated, etc.
- [x] Register the SharedTask model in the admin.py

**Comment by marked-gil** [comment]
User story is completed.
