### ISSUE TITLE
User Story: Category Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#17]
As a developer, I can save categories to the database so tasks are categorized.

### ACCEPTANCE CRITERIA:
- The Category model includes fields, such as owner, category_name, description, datetime_created, datetime_updated, etc.
- The Category model is available in the admin panel.

### TASKS:
- [x] Create ‘categories’ app
- [x] Add the ‘categories’ app in settings.py’s INTALLED_APPS
- [x] Create a Category model with fields, such as owner, category_name, description, datetime_created, datetime_updated, etc.
- [x] Register the Category model in the admin.py

**Comment by marked-gil** [comment]
User story completed.
