### ISSUE TITLE
User Story: Comment Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#18]
As a developer, I can allow users to create comments on tasks and save them in the database.

### ACCEPTANCE CRITERIA:
- The Comment model includes fields, such as id, owner, content, datetime_created, datetime_updated, task, reply_to, is_reply_to_comment, etc.
- The Comment model is available in the admin panel.

### TASKS:
- [x] Create ‘comments’ app
- [x] Add the ‘comments’ app in settings.py’s INSTALLED_APPS
- [x] Create a Comment model with fields, such as id, owner, content, datetime_created, datetime_updated, task, reply_to, is_reply_to_comment, etc.
- [x] Register the Comment model in the admin.py

**Comment by marked-gil** [comment]
User story is completed.
