### ISSUE TITLE
User Story: Notification Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#19]
As a developer, I can save notifications in the database so I can use and display them in the front end.

### ACCEPTANCE CRITERIA:
- The Notification model includes fields, such as id, message, sender, receiver, is_seen, task, comment, etc.
- The Notification model is available in the admin panel.

### TASKS:
- [ ] Create ‘notifications’ app
- [ ] Add the ‘notifications’ app in settings.py’s INSTALLED_APPS
- [ ] Create the Notification model with fields, such as id, message, sender, receiver, is_seen, task, comment, etc.
- [ ] Register the Notification model in the admin.py
