### ISSUE TITLE
User Story: Profile List

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#27]
As a developer, I can return a list of all profiles when requested in the API.

### ACCEPTANCE CRITERIA:
- A list of all user profiles is outputted by the API when requested.

### TASKS:
- [x] Set up ProfileList view 
- [x] Set up the URL path to retrieve the list of profiles
- [x] Return a list of all profiles from the API as a response to a GET request

**Comment by marked-gil** [comment]
User story completed.
