### ISSUE TITLE
User Story: Profile Details

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#28]
As a developer, I can return the profile details of a user when requested in the API.

### ACCEPTANCE CRITERIA:
- The user’s profile details are outputted by the API  when requested using the user id.

### TASKS:
- [x] Set up ProfileDetails view
- [x] Set up the URL path to retrieve the user's profile details
- [x] Return the user’s profile details as a response to a GET request for a specific user id.
