### ISSUE TITLE
User Story: Update Profile

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#30]
As a developer, I can allow a user to update their image, email, first name, and last name.

### ACCEPTANCE CRITERIA:
- User’s image, first name, last name, and email can be edited by the account’s owner.
- Username cannot be changed.

### TASKS:
- [x] Allow user to update their image, first name, last name, and email address.
- [x] Prevent the editing of usernames.
- [x] Add a validation check for the uploaded image to prevent uploading of a large image that is beyond the set parameter.
