### ISSUE TITLE
User Story: Task List

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#32]
As a developer, I can return a list of all tasks when requested in the API.

### ACCEPTANCE CRITERIA:
- A list of all tasks is outputted by the API when requested.

### TASKS:
- [x] Set up TaskList view
- [x] Set up the URL path to retrieve the list of tasks
- [x] Return a list of all tasks from the API as a response to a GET request.

**Comment by marked-gil** [comment]
User story completed.
