### ISSUE TITLE
User Story: Task Detail

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#33]
As a developer, I can return the details of a task when requested in the API.

### ACCEPTANCE CRITERIA:
- The details of a task are outputted by the API when requested.

### TASKS:
- [x] Set up TaskDetails view
- [x] Set up the URL path to retrieve the user's task details
- [x] Return the details of a task as a response to a GET request.

**Comment by marked-gil** [comment]
User Story completed.
