### ISSUE TITLE
User Story: SharedTask List

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#37]
As a developer, I can return a list of all shared tasks when requested in the API.

### ACCEPTANCE CRITERIA:
- A list of all shared tasks is outputted by the API when requested.

### TASKS:
- [x] Set up SharedTaskList view
- [x] Set up the URL path to retrieve the list of shared tasks
- [x] Return a list of all shared tasks from the API as a response to a GET request.

**Comment by marked-gil** [comment]
User story is completed.
