### ISSUE TITLE
User Story: SharedTask Details

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#38]
As a developer, I can return the details of a task when requested in the API.

### ACCEPTANCE CRITERIA:
- The details of a shared task are outputted by the API when requested.

### TASKS:
- [x] Set up SharedTaskDetails view
- [x] Set up the URL path to retrieve the shared task's details
- [x] Return the details of a shared task as a response to a GET request

**Comment by marked-gil** [comment]
User story is completed.
