### ISSUE TITLE
User Story: Category List

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#42]
As a developer, I can return a list of all categories when requested in the API.

### ACCEPTANCE CRITERIA:
- A list of all categories is outputted by the API when requested.

### TASKS:
- [x] Set up CategoryList view
- [x] Set up the URL path to retrieve the list of categories
- [x] Return a list of all categories from the API as a response to a GET request.

**Comment by marked-gil** [comment]
User story completed.
