### ISSUE TITLE
User Story: Category Details

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#43]
As a developer, I can return the details of a task when requested in the API.

### ACCEPTANCE CRITERIA:
- The details of a category are outputted by the API when requested.

### TASKS:
- [x] Set up CategoryDetails view
- [x] Set up the URL path to retrieve a category's details
- [x] Return the details of a category as a response to a GET request.

**Comment by marked-gil** [comment]
User story is completed.
