### ISSUE TITLE
User Story: Comment List

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#47]
As a developer, I can return a list of all comments when requested in the API.

### ACCEPTANCE CRITERIA:
- A list of all comments is outputted by the API when requested.

### TASKS:
- [x] Set up CommentList view
- [x] Set up the URL path to retrieve the list of comments
- [x] Return a list of all comments from the API as a response to a GET request

**Comment by marked-gil** [comment]
User story is completed.
