### ISSUE TITLE
User Story: Comment Details

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#48]
As a developer, I can return the details of a comment when requested in the API.

### ACCEPTANCE CRITERIA:
- The details of a comment are outputted by the API when requested.

### TASKS:
- [x] Set up CommentDetails view
- [x] Set up the URL path to retrieve the comment's details
- [x] Return the details of a comment as a response to a GET request.

**Comment by marked-gil** [comment]
User story is completed.
