### ISSUE TITLE
User Story: Restrict API Data to Authenticated Users Only

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#57]
As a developer, I want only authenticated (logged in) to view any data from the API.

### ACCEPTANCE CRITERIA:
- Login and logout buttons are displayed on the API browser
- Only logged-in users can view any data from the API

### TASKS:
- [x] Add login and logout buttons on the browsable API using login and logout views
- [x] Allow only logged-in users to view API data.
- [x] Install dj-rest-auth library to handle User Registration and Authentication tasks.
- [x] Install djangorestframework-simplejwt to add JWT authentication functionality.

**Comment by marked-gil** [comment]
User story is completed.
