### ISSUE TITLE
User Story: Restrict Retrieval of Data to their Owners and/or Permitted Users Only

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#58]
As a developer, I can only allow authenticated owners and permitted users to retrieve their data.

### ACCEPTANCE CRITERIA:
- Tasks are returned only to their logged-in owners.
- Shared tasks are returned only to their logged-in owners and permitted users.
- Categories are returned only to their logged-in owners.
- Comments are returned only to their logged-in owners and permitted users.

### TASKS:
- [x] Allow only logged-in owners to retrieve their tasks.
- [x] Allow only logged-in owners and permitted users to retrieve shared tasks.
- [x] Allow only logged-in owners to retrieve their category.
- [x] Allow only logged-in owners and permitted users to retrieve their comments.

## EPIC: #10

**Comment by marked-gil** [comment]
User story is completed.
