### ISSUE TITLE
User Story: Restrict Editing of Data to the Owner of the Data

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#59]
As a developer, I can allow the logged-in user who owns or created the data to modify it.

### ACCEPTANCE CRITERIA:
- Only the logged-in user who owns the profile can modify it.
- Only the logged-in user who created the task can modify it.
- Only the logged-in user who shared the task can edit the users sharing the task.
- Only the logged-in user who created the category can modify it.
- Only the logged-in user who created the comment can modify it.

### TASKS:
- [ ] Allow only the logged-in user who owns the profile to modify it.
- [ ] Allow only the logged-in user who created the task to modify it.
- [ ] Allow only the logged-in user who shared the task to edit the users sharing the task.
- [ ] Allow only the logged-in user who created the category to modify it.
- [ ] Allow only the logged-in user who created the comment to modify it.

**Comment by marked-gil** [comment]
User story is completed.
