### ISSUE TITLE
User Story: Restrict Deletion of Data to Authenticated Owners Only

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#60]
As a developer, I can only allow authenticated users to delete their own tasks, shared tasks, categories, and comments.

### ACCEPTANCE CRITERIA:
- Only logged-in users can delete their own tasks.
- Only logged-in users/owners can remove all other users from sharing a task.
- Only logged-in users can delete their created categories.
- Only logged-in users can delete their own comments.

### TASKS:
- [x] Allow only logged-in users to delete their own tasks.
- [x] Allow only logged-in. owners to delete their shared tasks.
- [x] Allow only logged-in users to delete their created categories.
- [x] Allow only logged-in users to delete their own comments.

**Comment by marked-gil** [comment]
User story is completed.
