### ISSUE TITLE
User Story: Connect Database and Heroku

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#63]
As a developer, I want to create the production database and connect it to Heroku.

### ACCEPTANCE CRITERIA:
- Database instance in ElephantSQL and Heroku app are created.

### TASKS:
- [x] Create database instance in ElephantSQL.com
- [x] Create Heroku app
- [x] Add the DB URL to Heroku app’s config vars
- [x] Install dj_database_url==0.5.0 psycopg2, which is needed to connect to external database
