### ISSUE TITLE
User Story: Allow User Registration

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#66]
As a developer, I can allow user registration using dj-rest-auth library.

### ACCEPTANCE CRITERIA:
- Users can register to the API.

### TASKS:
- [x] Install 'dj-rest-auth[with_social]'
- [x] Add the following to INSTALLED_APPS: django.contrib.sites, allauth, allauth.account, allauth.socialaccount and dj_rest_auth.registration
- [x] "SITE_ID = 1" in settings.py
- [x] Add dj_rest_auth.registration urls
