### ISSUE TITLE
User Story: Filter Task List in the API

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-api#67]
As a developer, I can allow filtering of tasks by ordering, searching, and using filterset.

### ACCEPTANCE CRITERIA:
- Tasks can be organized by ordering results
- Tasks can be searched by category, and task name
- Tasks can be filtered by due_dates, priority, progress, category

### TASKS:
- [x] Install django_filters and add it to INSTALLED_APPS
- [x] Add OrderingFilter and fields, such as due_date, due_time, priority
- [x] Add SearchFilter and fields, such as category, and task name
- [x] Add filterset_fields, such as due_date, priority, progress, category

**Comment by marked-gil** [comment]
User story is completed.
